import { Bug } from './interface/Bug';

export const Bugs: Bug[] = [
  {
    id: '4d75p7684z05-owf8',
    severity: 'High',
    created: 'Thu Aug 11 2022 11:16:00 GMT+0100 (West Africa Standard Time)',
    platform: 'XPath',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Amelia Feil',
      email: 'Camylle@B2B.org',
    },
    label: 'Velit voluptas harum.',
    status: 'open',
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design. The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design. The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design. The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design.',
  },
  {
    id: '4d75d7684f05-bbf8',
    severity: 'Normal',
    created: 'Tue Jul 26 2022 10:22:48 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Amelia Feil',
      email: 'Camylle@B2B.org',
    },
    label: 'Velit voluptas harum.',
    status: 'closed',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Eugene Turcotte',
    },
    description: 'Ea magni nesciunt enim et deleniti.',
  },
  {
    id: '9809eb8c910e-86fc',
    severity: 'Low',
    created: 'Thu Jun 02 2022 19:23:50 GMT+0100 (West Africa Standard Time)',
    platform: 'Internet Banking',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Moses Brekke',
      email: 'Colton@compelling.org',
    },
    label: 'Vel ut laudantium necessitatibus iusto earum.',
    status: 'closed',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Rodolfo Bins',
    },
    description:
      'Libero pariatur facilis vel officiis labore consequatur cupiditate. Tempora officiis blanditiis. Tenetur architecto nostrum repellat soluta possimus eaque. Atque quibusdam ex. Sint dicta maiores et qui temporibus omnis.',
  },
  {
    id: 'b2b080ddb297-a8de',
    severity: 'High',
    created: 'Wed Jul 20 2022 13:07:58 GMT+0100 (West Africa Standard Time)',
    platform: 'Form A',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Dr. Brittany DuBuque',
      email: 'Darian@efficient.org',
    },
    label: 'Excepturi placeat unde et.',
    status: 'open',
    description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016. The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design.. The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design.',
  },
  {
    id: 'cc60318c5a56-a802',
    severity: 'Low',
    created: 'Thu Sep 23 2021 13:14:49 GMT+0100 (West Africa Standard Time)',
    platform: 'Workflow',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Terry Turcotte',
      email: 'Gust@visionary.org',
    },
    label: 'Qui consequatur optio qui sint suscipit temporibus sunt.',
    status: 'open',
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
  },
  {
    id: '13ae8ec4c695-8370',
    severity: 'Low',
    created: 'Sun May 01 2022 11:48:28 GMT+0100 (West Africa Standard Time)',
    platform: 'Form A',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Jana Welch',
      email: 'Sydni@B2C.org',
    },
    label: 'Veritatis eius omnis et veritatis officiis qui unde.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Spencer Kuvalis',
    },
    description:
      'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',
  },
  {
    id: '99bae23a27e8-b656',
    severity: 'Low',
    created: 'Sat Oct 30 2021 02:50:42 GMT+0100 (West Africa Standard Time)',
    platform: 'Workflow',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Darrel Jast',
      email: 'Waylon@Open-source.org',
    },
    label: 'In sunt non sunt voluptas.',
    status: 'open',
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
  },
  {
    id: 'c2c9819464d1-8f1d',
    severity: 'Normal',
    created: 'Wed Nov 24 2021 21:32:24 GMT+0100 (West Africa Standard Time)',
    platform: 'Workflow',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Glen Blanda',
      email: 'Don@intuitive.org',
    },
    label:
      'Dolorem laboriosam velit sunt necessitatibus vel odit quidem saepe.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Tara MacGyver',
    },
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
  },
  {
    id: '1f59cda74dcb-9771',
    severity: 'Normal',
    created: 'Fri Aug 27 2021 00:02:24 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Mattie Medhurst',
      email: 'Caitlyn@magnetic.org',
    },
    label: 'Est dicta modi quod in ad ab est sed.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Hattie Graham',
    },
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
  },
  {
    id: '300fce9032b0-8ad4',
    severity: 'High',
    created: 'Fri Sep 03 2021 02:39:20 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Mr. Dustin Kunze',
      email: 'Keshawn@next-generation.org',
    },
    label: 'Et laborum aut.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Rex Gutmann',
    },
    description: 'The Football Is Good For Training And Recreational Purposes',
  },
  {
    id: 'e11ebbff95cf-8a56',
    severity: 'High',
    created: 'Mon Sep 20 2021 00:41:49 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Cedric Yost',
      email: 'Domingo@value-added.org',
    },
    label: 'At molestiae corporis.',
    status: 'closed',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Cynthia Collins',
    },
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
  },
  {
    id: 'dec5f25a6ae5-a124',
    severity: 'High',
    created: 'Tue Jul 12 2022 02:59:07 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Beatrice Reinger',
      email: 'Mireille@sexy.org',
    },
    label: 'Veniam accusamus occaecati.',
    status: 'closed',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Kari Bartell',
    },
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
  },
  {
    id: '820c48c17093-a842',
    label: 'Labore omnis fugit officiis temporibus delectus.',
    platform: 'USSD',
    severity: 'High',
    created: 'Sun Feb 27 2022 03:04:24 GMT+0100 (West Africa Standard Time)',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Edgar Jerde',
      email: 'Garnet@bleeding-edge.org',
    },
    status: 'open',
    description: 'The Football Is Good For Training And Recreational Purposes',
  },
  {
    id: '5d809a0e4cf8-96d1',
    severity: 'Normal',
    created: 'Thu Apr 14 2022 03:12:01 GMT+0100 (West Africa Standard Time)',
    platform: 'Appraisal',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Steve Rath',
      email: 'Glen@plug-and-play.org',
    },
    label: 'Velit quia quam quasi qui tempore.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Javier Torp',
    },
    description:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: '531c037f9ba5-85e3',
    severity: 'Normal',
    created: 'Mon Dec 20 2021 21:16:52 GMT+0100 (West Africa Standard Time)',
    platform: 'Workflow',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Traci Will',
      email: 'Miguel@wireless.org',
    },
    label: 'Officiis est et commodi libero quidem repellat in non iusto.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Brian Rogahn V',
    },
    description: 'The Football Is Good For Training And Recreational Purposes',
  },
  {
    id: 'dd5f7544e10c-b9eb',
    severity: 'Normal',
    created: 'Tue Jun 14 2022 22:05:03 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Mrs. Phil Botsford',
      email: 'Jaida@real-time.org',
    },
    label: 'Iste voluptatem maxime maiores earum est non earum.',
    status: 'open',
    description: 'The Football Is Good For Training And Recreational Purposes',
  },
  {
    id: '4c10f0c1ac98-a9ea',
    severity: 'Normal',
    created: 'Mon Mar 14 2022 02:55:37 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Julius Schroeder',
      email: 'Merritt@end-to-end.org',
    },
    label: 'Ea accusantium modi consequatur labore.',
    status: 'open',
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
  },
  {
    id: 'dbbc66a237f5-b780',
    severity: 'Low',
    created: 'Sat Jul 23 2022 23:43:20 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Traci Willms PhD',
      email: 'Malvina@collaborative.org',
    },
    label: 'Iure explicabo voluptatem nobis est.',
    status: 'open',
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
  },
  {
    id: 'fd9cf2321659-a19f',
    severity: 'Low',
    created: 'Wed Jul 20 2022 02:49:12 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Miss Rudy Schaden',
      email: 'Rhett@intuitive.org',
    },
    label: 'Nobis rerum ipsam.',
    status: 'open',
    description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
  },
  {
    id: 'caa57cb83377-be58',
    severity: 'Normal',
    created: 'Tue Aug 24 2021 12:15:57 GMT+0100 (West Africa Standard Time)',
    platform: 'Workflow',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Lola Boyer',
      email: 'Fernando@virtual.org',
    },
    label: 'Id blanditiis est voluptatibus corporis aliquid ratione est.',
    status: 'open',
    description:
      'Carbonite web goalkeeper gls are ergonomically designed to give easy fit',
  },
  {
    id: '10034d5d8bee-b04d',
    severity: 'Normal',
    created: 'Mon Oct 18 2021 08:49:25 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Luther Schowalter',
      email: 'Tierra@bleeding-edge.org',
    },
    label: 'Cupiditate ut ullam harum deserunt omnis consequatur.',
    status: 'open',
    description:
      'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
  },
  {
    id: 'c6a6e1d8d1a7-818f',
    severity: 'Normal',
    created: 'Wed Jun 22 2022 16:21:46 GMT+0100 (West Africa Standard Time)',
    platform: 'Form A',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Saul Kassulke',
      email: 'Crawford@sexy.org',
    },
    label: 'Animi ut deleniti deserunt neque optio quia eaque cumque.',
    status: 'open',
    description:
      'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
  },
  {
    id: '7be33ace9761-8055',
    severity: 'Normal',
    created: 'Thu Aug 12 2021 04:29:31 GMT+0100 (West Africa Standard Time)',
    platform: 'Form A',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Debbie Grant',
      email: 'Dante@strategic.org',
    },
    label: 'Fugit quidem ipsa repellat praesentium.',
    status: 'open',
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
  },
  {
    id: 'b79a3456f869-ae1c',
    severity: 'Normal',
    created: 'Wed Dec 29 2021 08:10:12 GMT+0100 (West Africa Standard Time)',
    platform: 'Form A',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Forrest Hoeger II',
      email: 'Judy@seamless.org',
    },
    label: 'Ad mollitia quo suscipit ut suscipit iure quos est et.',
    status: 'open',
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
  },
  {
    id: '86936eb68384-be4e',
    severity: 'Normal',
    created: 'Thu Dec 23 2021 20:37:35 GMT+0100 (West Africa Standard Time)',
    platform: 'Form A',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Phil Senger MD',
      email: 'Skye@transparent.org',
    },
    label: 'Quia quas unde amet.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Damon Dicki',
    },
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
  },
  {
    id: '08aa9a2e178c-9430',
    severity: 'Normal',
    created: 'Mon Aug 01 2022 20:00:16 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Lynne Carroll',
      email: 'Ima@innovative.org',
    },
    label: 'Corrupti deserunt aut ipsam ut sapiente non.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Mrs. Dora Langosh',
    },
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
  },
  {
    id: 'f92a412bb86d-a7ce',
    severity: 'Normal',
    created: 'Thu Apr 14 2022 09:40:29 GMT+0100 (West Africa Standard Time)',
    platform: 'USSD',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Mrs. Kelly Olson',
      email: 'Christopher@magnetic.org',
    },
    label: 'In sit expedita.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Juana Cassin',
    },
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
  },
  {
    id: 'caa3b6c10ff0-a7dc',
    severity: 'Normal',
    created: 'Fri Dec 03 2021 20:14:46 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Ken Mante',
      email: 'Mireya@end-to-end.org',
    },
    label: 'Ea consectetur sint a illum quo quam.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: "Laura O'Hara",
    },
    description: 'The Football Is Good For Training And Recreational Purposes',
  },
  {
    id: 'be8d8cdc1ab0-94a8',
    severity: 'Normal',
    created: 'Wed Jul 13 2022 16:23:21 GMT+0100 (West Africa Standard Time)',
    platform: 'Appraisal',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Stanley Ruecker',
      email: 'Enid@sticky.org',
    },
    label: 'Cum magni sint et veritatis nobis numquam accusamus natus.',
    status: 'open',
    description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
  },
  {
    id: 'b75233bb3973-9018',
    severity: 'Normal',
    created: 'Fri Jul 15 2022 08:06:08 GMT+0100 (West Africa Standard Time)',
    platform: 'USSD',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Gilberto Fisher',
      email: 'Ellen@front-end.org',
    },
    label: 'Reiciendis qui consectetur quis nesciunt unde fugit sunt.',
    status: 'open',
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
  },
  {
    id: '6a4568d87d0e-be26',
    severity: 'Low',
    created: 'Wed Jun 15 2022 08:28:01 GMT+0100 (West Africa Standard Time)',
    platform: 'USSD',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Mr. Alfonso Witting',
      email: 'Elliott@cross-media.org',
    },
    label: 'Et qui perspiciatis aut.',
    status: 'open',
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
  },
  {
    id: '7135dc270c78-9065',
    severity: 'Low',
    created: 'Fri Jun 17 2022 10:18:05 GMT+0100 (West Africa Standard Time)',
    platform: 'USSD',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Miss Ira Collins',
      email: 'Bartholome@viral.org',
    },
    label: 'Quia sequi voluptatem est at ad est quidem et iste.',
    status: 'open',
    description:
      'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
  },
  {
    id: '4fe79af8d9e1-bf63',
    severity: 'Normal',
    created: 'Thu Sep 23 2021 16:02:21 GMT+0100 (West Africa Standard Time)',
    platform: 'USSD',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Miss Allen Green',
      email: 'Corine@bleeding-edge.org',
    },
    label: 'Tenetur nihil non sunt vel adipisci libero.',
    status: 'open',
    description: 'The Football Is Good For Training And Recreational Purposes',
  },
  {
    id: '2f60dbd456e8-bf8e',
    severity: 'High',
    created: 'Thu Sep 16 2021 06:24:59 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Mrs. Antonia Reichel',
      email: 'Clementina@interactive.org',
    },
    label:
      'Nam veritatis molestiae et praesentium consequatur id maiores temporibus.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Mrs. Sheila Marks',
    },
    description:
      'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
  },
  {
    id: '7f92bb44698a-a214',
    severity: 'High',
    created: 'Sun May 29 2022 15:52:53 GMT+0100 (West Africa Standard Time)',
    platform: 'Appraisal',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Lyle Lind',
      email: 'Wyatt@real-time.org',
    },
    label: 'Et maxime quidem in blanditiis maiores.',
    status: 'pending',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Leona Crooks',
    },
    description:
      'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
  },
  {
    id: '95bc71427b96-aa95',
    severity: 'Low',
    created: 'Sun Jul 10 2022 09:28:20 GMT+0100 (West Africa Standard Time)',
    platform: 'Mobile App',
    reporter: {
      id: 20220011,
      img: 'https://placeimg.com/100/100/people',
      name: 'Ida Abernathy',
      email: 'Cicero@customized.org',
    },
    label: 'Voluptatem repellat odit.',
    status: 'closed',
    developer: {
      id: 20220010,
      img: '//joeschmoe.io/api/v1/random',
      name: 'Camille Cronin',
    },
    description:
      'Lorem in commodo nostrud deserunt est Lorem dolor minim irure reprehenderit. Exercitation commodo enim aute incididunt amet consectetur officia sit cupidatat magna consequat proident enim. Ex nulla adipisicing dolor sint veniam. Reprehenderit ea non ea culpa. Laboris velit occaecat enim nisi laborum occaecat cupidatat cillum sunt aliqua.',
  },
];

export const Developer = [
  {
    id: 20220001,
    img: 'https://placeimg.com/100/100/people',
    name: 'Roxanne Nicolas',
    firstSignin:
      'Thu Dec 16 2021 12:50:30 GMT+0100 (West Africa Standard Time)',
    contributions: '211',
    branch: 'Kentucky',
    department: 'Bike',
  },
  {
    id: 20220002,
    img: 'https://placeimg.com/100/100/people',
    name: 'Mrs. Kent Sanford',
    firstSignin:
      'Sun Dec 05 2021 13:11:51 GMT+0100 (West Africa Standard Time)',
    contributions: '8',
    branch: 'New Hampshire',
    department: 'digital',
  },
  {
    id: 20220003,
    img: 'https://placeimg.com/100/100/people',
    name: 'Ed Sporer DVM',
    firstSignin:
      'Thu Mar 17 2022 23:19:11 GMT+0100 (West Africa Standard Time)',
    contributions: '250',
    branch: 'New York',
    department: 'proactive',
  },
  {
    id: 20220004,
    img: 'https://placeimg.com/100/100/people',
    name: 'Mrs. Marvin Champlin',
    firstSignin:
      'Sat Jan 15 2022 21:50:41 GMT+0100 (West Africa Standard Time)',
    contributions: '500',
    branch: 'Texas',
    department: 'GB',
  },
  {
    id: 20220005,
    img: 'https://placeimg.com/100/100/people',
    name: 'Sherry Will DVM',
    firstSignin:
      'Sat May 28 2022 23:45:09 GMT+0100 (West Africa Standard Time)',
    contributions: '333',
    branch: 'Illinois',
    department: 'Concrete',
  },
  {
    id: 20220006,
    img: 'https://placeimg.com/100/100/people',
    name: 'Mr. Kay Senger',
    firstSignin:
      'Fri Sep 02 2022 15:43:54 GMT+0100 (West Africa Standard Time)',
    contributions: '374',
    branch: 'Pennsylvania',
    department: 'index',
  },
  {
    id: 20220007,
    img: 'https://placeimg.com/100/100/people',
    name: 'Preston Schoen',
    firstSignin:
      'Wed Aug 24 2022 09:43:55 GMT+0100 (West Africa Standard Time)',
    contributions: '654',
    branch: 'Michigan',
    department: 'Utah',
  },
  {
    id: 20220008,
    img: 'https://placeimg.com/100/100/people',
    name: 'Faith Parisian Jr.',
    firstSignin:
      'Sat Aug 06 2022 20:04:08 GMT+0100 (West Africa Standard Time)',
    contributions: '161',
    branch: 'Connecticut',
    department: 'Avon',
  },
  {
    id: 20220010,
    img: 'https://placeimg.com/100/100/people',
    name: 'Joanna Rice',
    firstSignin:
      'Sat Aug 20 2022 23:49:24 GMT+0100 (West Africa Standard Time)',
    contributions: '466',
    branch: 'West Virginia',
    department: 'HTTP',
  },
  {
    id: 20220011,
    img: 'https://placeimg.com/100/100/people',
    name: 'Blanche Reilly',
    firstSignin:
      'Fri May 20 2022 19:01:44 GMT+0100 (West Africa Standard Time)',
    contributions: '788',
    branch: 'Iowa',
    department: 'schemas',
  },
  {
    id: 20220012,
    img: 'https://placeimg.com/100/100/people',
    name: 'Terry Nader',
    firstSignin:
      'Fri May 06 2022 15:59:38 GMT+0100 (West Africa Standard Time)',
    contributions: '58',
    branch: 'Arkansas',
    department: 'Computers',
  },
  {
    id: 20220013,
    img: 'https://placeimg.com/100/100/people',
    name: 'Douglas Mosciski',
    firstSignin:
      'Sun Jun 26 2022 02:16:29 GMT+0100 (West Africa Standard Time)',
    contributions: '85',
    branch: 'South Dakota',
    department: 'Islands',
  },
];
